// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtTSMxPAxR7WsI_m5AAhfJWFdwd9QIxg',
    appId: '1:44432274157:web:9855514233aee9b784d2e4',
    messagingSenderId: '44432274157',
    projectId: 'cmms2020-11ee8',
    authDomain: 'cmms2020-11ee8.firebaseapp.com',
    storageBucket: 'cmms2020-11ee8.appspot.com',
    measurementId: 'G-X3BKV4W4Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrSJlDZrYFy4KrIb3ZSSoCg8VOaA0c_o',
    appId: '1:44432274157:android:caf6011f6e6e4a0784d2e4',
    messagingSenderId: '44432274157',
    projectId: 'cmms2020-11ee8',
    storageBucket: 'cmms2020-11ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTzbrBn7zxYfwdB-IuPMBH3LNvDSngN08',
    appId: '1:44432274157:ios:d2d18f446f9dcaa184d2e4',
    messagingSenderId: '44432274157',
    projectId: 'cmms2020-11ee8',
    storageBucket: 'cmms2020-11ee8.appspot.com',
    iosClientId: '44432274157-fpdoi2shsf246fj7uag477ab3q8kmeei.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmms',
  );
}
